### PR TITLE
Fix slow select_recent_images query to use index

### PR DESCRIPTION
**Pull request by mwest1066**

### CODE REVIEW

**Comment by mwest1066** [comment]
I just realized I didn't describe the problem here. This query has been taking an average of 40 seconds to run, which slows down grader start (this query must execute before the grader will start accepting jobs). The reason it's so slow is that the `grading_jobs` table has become very large, and we don't have an index on `grading_jobs.grading_requested_at`. I changed the date restriction to use `submissions.date`, which is indexed. This query was responsible for all of the full table scans of `grading_jobs`, so we'll hopefully significantly improve our index scan stats once this fix is live.

Now that I think about it, it's probably more consistent to use `grading_jobs.date`, which is also indexed. I doubt it will make much difference either way, assuming the query planner is doing its job.

**Comment by nwalters512** [comment]
Good catch! Did anything in particular prompt you to look at this query in particular?

`submissions.date` sounds fine to me, as long as the query planner is indeed operating as expected. Do you have data point for how long the new version of the query takes to run?

**Comment by mwest1066** [comment]
I noticed this query while checking our nightly dbstats -- I was just idly looking while thinking about how to debug our `idle-in-transaction-timeout` problems. This query showed up near the top of the `top100_queries_by_mean_time` and was obviously waaaaaay too slow.

Embarrassingly I did not test the replacement query 😄 I just ran it now and it took 18 ms, so I think we can call that an improvement (2000x speedup, I love indexes!).

**Comment by nwalters512** [comment]
Gotcha 👍 would be nice to have alerts of long-running queries be automated. I'll add that to my wishlist for when we hire a SRE-like person 😂 

2000x, woot! Small change for a huge win.

**Comment by mwest1066** [comment]
Automating that would be great! At the moment the other slow queries are the nightly backups (no surprise there), and the gradebook page query which takes about 2 seconds for a large class. I haven't investigated that one to see whether it can be optimized.

**Pull request merged**
